### ISSUE TITLE
modify Horace installation script to enable parallel extensions

### ISSUE THREAD

**Issue by abuts** [pace-neutrons/euphonic-validation#1]
Horace tests currently fail on this branch because when attempt to enable horace tests is made,  the script fails due to parallel extensions are missing. 

This should be easily fixable

**Comment by rebeccafair** [comment]
I think this issue might've been opened in the wrong repository by mistake. Did you mean to put this in the Horace repo?

**Comment by abuts** [comment]
As I do not have access rights to these repo, I've created and sent @rebeccafair the patch, which should fix the issue as soon as [#704](https://github.com/pace-neutrons/Horace/pull/704) is merged and built.
